INSERT INTO Football_Teams(ID,City,Team_Name,QB,RB,WR,TE,OL,DL,LB,CB,S,K,Coach,Momentum,Timezone)
VALUES (1,'New York','Giants','C+', 'A', 'D+', 'B', 'D-', 'B', 'C-','D+','D+','B','B','Neutral',1),
       (2,'Dallas','Cowboys','B-', 'B', 'B+', 'D+', 'B+', 'B', 'C', 'A-', 'A-', 'D-','B','Neutral',2),
	   (3,'Philadelphia','Eagles','B', 'C', 'A', 'B-', 'A+', 'A', 'C', 'A', 'A', 'B','A','Neutral',1),
       (4,'Washington','Commanders','D+', 'D+', 'B-', 'D', 'D', 'C', 'D+', 'B', 'C-', 'D+','C','Neutral',1),
	   (5,'New Orleans','Saints','C', 'C+', 'C', 'C', 'D+', 'B', 'A-','C-','B+','D+','B','Neutral',2),
       (6,'Atlanta','Falcons','D+', 'B', 'C', 'B-', 'B', 'B', 'D', 'C-', 'B', 'A','B','Neutral',1),
	   (7,'Tampa Bay','Buccaneers','C-', 'D', 'B', 'D', 'C', 'A', 'B', 'B-', 'A', 'D','A','Neutral',1),
       (8,'Carolina','Panthers','D+', 'D+', 'D', 'D', 'C', 'C', 'C', 'C-', 'C-','C','C','Neutral',1),
       (9,'Settle','Seahawks','B', 'B-', 'A-', 'C', 'D-', 'B', 'B+','C','D+','B','B','Neutral',4),
       (10,'Arizona','Cardinals','D+', 'D', 'D', 'B-', 'D-', 'B', 'D+', 'D', 'B', 'C-','B','Neutral',4),
	   (11,'San Francisco','49ers','C+', 'A+', 'B', 'A-', 'C', 'A', 'A+', 'B+', 'B', 'D','A','Neutral',4),
       (12,'Los Angeles','Rams','B', 'D-', 'B', 'C', 'D', 'C', 'D-', 'D-', 'D-', 'D','C','Neutral',4),
	   (13,'Green Bay','Packers','C', 'C+', 'C-', 'C', 'B', 'B', 'C','C','C','D-','B','Neutral',2),
       (14,'Lions','Detroit','C+', 'C', 'B-', 'C-', 'A-', 'B', 'C-', 'C-', 'C', 'D+','B','Neutral',1),
	   (15,'Minnesota','Vikings','B-', 'D+', 'B+', 'B', 'C', 'A', 'D', 'D+', 'C-', 'C-','A','Neutral',2),
       (16,'Chicago','Bears','D+', 'C', 'C+', 'B-', 'C-', 'C', 'A', 'C', 'D', 'C','C','Neutral',2),
       (17,'Miami','Dolphins','B', 'C', 'A+', 'D', 'C-', 'B', 'B-','B+','B','C','B','Neutral',1),
       (18,'New England','Patriots','C-', 'C', 'D', 'C', 'C+', 'B', 'B-', 'B', 'B', 'C+','B','Neutral',1),
	   (19,'Bills','Buffalo','A', 'C-', 'B+', 'C-', 'C-', 'A', 'B-', 'B', 'B', 'A-','A','Neutral',1),
       (20,'New York','Jets','A-', 'B-', 'C', 'D+', 'D+', 'C', 'C-', 'A+', 'A+', 'C-','C','Neutral',1),
	   (21,'Tennessee','Titans','C', 'A-', 'B', 'C-', 'D-', 'B', 'D-','D','A','D-','B','Neutral',2),
       (22,'Indianapolis','Colts','D', 'A-', 'C-', 'D', 'B-', 'B', 'B', 'D-', 'D-', 'C','B','Neutral',1),
	   (23,'Jacksonville','Jaguars','B-', 'B-', 'C+', 'B-', 'D+', 'A', 'C', 'D', 'D', 'B-','A','Neutral',1),
       (24,'Houston','Texans','D', 'C+', 'D-', 'C+', 'D+', 'C', 'D', 'D-', 'C+', 'C','C','Neutral',2),
       (25,'Los Angeles','Chargers','B+', 'A-', 'B', 'C+', 'B-', 'B', 'C-','C+','A+','B-','B','Neutral',4),
       (26,'Los Vegas','Raiders','C+', 'A+', 'B', 'C-', 'C-', 'B', 'D-', 'D-', 'D-', 'A','B','Neutral',3),
	   (27,'Kansas City','Chiefs','A+', 'C', 'B-', 'A+', 'A', 'A', 'B+', 'B+', 'B+', 'B+','A','Neutral',2),
       (28,'Denver','Broncos','C+', 'C+', 'C', 'C-', 'C+', 'C', 'C+', 'A', 'B', 'D','C','Neutral',3),
       (29,'Pittsburgh','Steelers','C', 'B', 'C', 'B', 'C+', 'B', 'D+','C','A','C-','B','Neutral',1),
       (30,'Baltimore','Ravens','A-', 'C+', 'C', 'A', 'B+', 'B', 'A', 'A', 'D+', 'A+','B','Neutral',1),
	   (31,'Cincinnati','Bengals','A', 'B-', 'A', 'D', 'C', 'A', 'A-', 'C+', 'C+', 'A-','A','Neutral',1),
       (32,'Cleveland','Browns','B-', 'A', 'C+', 'B-', 'A', 'C', 'C', 'D+', 'D', 'C','C','Neutral',1);